/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rsa.aes;

import java.awt.Component;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.bind.DatatypeConverter;
import static rsa.aes.RSA.PRIVATE_KEY_FILE;
import static rsa.aes.RSA.PUBLIC_KEY_FILE;
import static rsa.aes.RSA.areKeysPresent;
import static rsa.aes.RSA.decrypt;
import static rsa.aes.RSA.encrypt;
import static rsa.aes.RSA.generateKey;

/**
 *
 * @author anony
 */
public class AES extends javax.swing.JFrame {

    /**
     * Creates new form AES
     */
    public AES() {
        initComponents();
    }

    String extension = "";
    String filename = "";
    String textPane1 = "";
    String textPane2 = "";
    Path path = null;
    Path raw_path = null;
    Path decrypted_path = null;
    byte[] encrypted;
    byte[] decrypted;
    boolean doneEncrypt = false;
    boolean doneDecrypt = false;
    byte[] clean = null;
    long time = 0;
    
   

    public static byte[] encrypt(byte[] clean, String key) throws Exception {
        byte ivSize = 16;
        byte[] iv = new byte[ivSize];
        SecureRandom random = new SecureRandom();
        random.nextBytes(iv);
        IvParameterSpec ivParameterSpec = new IvParameterSpec(iv);
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        digest.update(key.getBytes("UTF-8"));
        byte[] keyBytes = new byte[16];
        System.arraycopy(digest.digest(), 0, keyBytes, 0, keyBytes.length);
        SecretKeySpec secretKeySpec = new SecretKeySpec(keyBytes, "AES");
        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        cipher.init(1, secretKeySpec, ivParameterSpec);
        byte[] encrypted = cipher.doFinal(clean);
        byte[] encryptedIVAndText = new byte[ivSize + encrypted.length];
        System.arraycopy(iv, 0, encryptedIVAndText, 0, ivSize);
        System.arraycopy(encrypted, 0, encryptedIVAndText, ivSize, encrypted.length);
        return encryptedIVAndText;
    }

    public static byte[] decrypt(byte[] encryptedIvTextBytes, String key) throws Exception {
        byte ivSize = 16;
        byte keySize = 16;
        byte[] iv = new byte[ivSize];
        System.arraycopy(encryptedIvTextBytes, 0, iv, 0, iv.length);
        IvParameterSpec ivParameterSpec = new IvParameterSpec(iv);
        int encryptedSize = encryptedIvTextBytes.length - ivSize;
        byte[] encryptedBytes = new byte[encryptedSize];
        System.arraycopy(encryptedIvTextBytes, ivSize, encryptedBytes, 0, encryptedSize);
        byte[] keyBytes = new byte[keySize];
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        md.update(key.getBytes());
        System.arraycopy(md.digest(), 0, keyBytes, 0, keyBytes.length);
        SecretKeySpec secretKeySpec = new SecretKeySpec(keyBytes, "AES");
        Cipher cipherDecrypt = Cipher.getInstance("AES/CBC/PKCS5Padding");
        cipherDecrypt.init(2, secretKeySpec, ivParameterSpec);
        byte[] decrypted = cipherDecrypt.doFinal(encryptedBytes);
        return decrypted;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        BrowseTab1 = new javax.swing.JButton();
        Encrypt = new javax.swing.JButton();
        SaveAsEncrypt = new javax.swing.JButton();
        key = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        SaveEncrypt = new javax.swing.JButton();
        EncryptKey = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BrowseTab2 = new javax.swing.JButton();
        Decrypt = new javax.swing.JButton();
        SaveAsDecrypt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        SaveDecrypt = new javax.swing.JButton();
        DecryptKey = new javax.swing.JButton();
        BrowseEncryptKey = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        HashMd5Raw = new javax.swing.JButton();
        BrowseRawFile = new javax.swing.JButton();
        BrowseDecryptedFile = new javax.swing.JButton();
        HashMd5Decrypt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Checksum = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextPane1.setEditable(false);
        jScrollPane2.setViewportView(jTextPane1);

        BrowseTab1.setText("Browse");
        BrowseTab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseTab1ActionPerformed(evt);
            }
        });

        Encrypt.setText("Encrypt");
        Encrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncryptActionPerformed(evt);
            }
        });

        SaveAsEncrypt.setText("Save As");
        SaveAsEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsEncryptActionPerformed(evt);
            }
        });

        key.setText("Key");

        SaveEncrypt.setText("Save");
        SaveEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveEncryptActionPerformed(evt);
            }
        });

        EncryptKey.setText("Encrypt K");
        EncryptKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncryptKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(key)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SaveEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SaveAsEncrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Encrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BrowseTab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EncryptKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EncryptKey))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BrowseTab1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Encrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveEncrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveAsEncrypt)))
                .addGap(36, 36, 36))
        );

        jTabbedPane1.addTab("Encrypt", jPanel1);

        BrowseTab2.setText("Browse");
        BrowseTab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseTab2ActionPerformed(evt);
            }
        });

        Decrypt.setText("Decrypt");
        Decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecryptActionPerformed(evt);
            }
        });

        SaveAsDecrypt.setText("Save As");
        SaveAsDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsDecryptActionPerformed(evt);
            }
        });

        jTextPane2.setEditable(false);
        jScrollPane1.setViewportView(jTextPane2);

        jLabel4.setText("Key ");

        SaveDecrypt.setText("Save");
        SaveDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDecryptActionPerformed(evt);
            }
        });

        DecryptKey.setText("Decrypt K");
        DecryptKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecryptKeyActionPerformed(evt);
            }
        });

        BrowseEncryptKey.setText("Browse K");
        BrowseEncryptKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseEncryptKeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BrowseEncryptKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BrowseTab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Decrypt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SaveDecrypt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SaveAsDecrypt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DecryptKey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrowseEncryptKey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DecryptKey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BrowseTab2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Decrypt)
                        .addGap(8, 8, 8)
                        .addComponent(SaveDecrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveAsDecrypt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Decrypt", jPanel2);

        jLabel3.setText("Raw File");

        jTextField3.setEditable(false);
        jTextField3.setAutoscrolls(false);

        jTextField4.setEditable(false);
        jTextField4.setAutoscrolls(false);

        jLabel5.setText("Decrypted File");

        HashMd5Raw.setText("Hash MD5");
        HashMd5Raw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HashMd5RawActionPerformed(evt);
            }
        });

        BrowseRawFile.setText("Browse");
        BrowseRawFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseRawFileActionPerformed(evt);
            }
        });

        BrowseDecryptedFile.setText("Browse");
        BrowseDecryptedFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseDecryptedFileActionPerformed(evt);
            }
        });

        HashMd5Decrypt.setText("Hash MD5");
        HashMd5Decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HashMd5DecryptActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        Checksum.setText("Check");
        Checksum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChecksumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Checksum, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField3)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(BrowseRawFile)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HashMd5Raw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(BrowseDecryptedFile)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HashMd5Decrypt))))))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrowseRawFile)
                    .addComponent(HashMd5Raw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BrowseDecryptedFile)
                    .addComponent(HashMd5Decrypt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Checksum)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Checksum", jPanel3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hybrid Encryption");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel2.setText("Made by Nhu Dinh Toan (1414060)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChecksumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChecksumActionPerformed
        // TODO add your handling code here:
        text += hash_raw.equalsIgnoreCase(hash_decrypted) ? "MATCH" : "NO MATCH";
        JOptionPane.showMessageDialog((Component)null, text);
        jTextArea1.setText(text + "\n");
        text = "";
    }//GEN-LAST:event_ChecksumActionPerformed

    private void HashMd5DecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HashMd5DecryptActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            byte[] file = Files.readAllBytes(decrypted_path);
            byte[] hash = MessageDigest.getInstance("MD5").digest(file);
            hash_decrypted = DatatypeConverter.printHexBinary(hash);
            text += "Decrypted file hashed to MD5 is: " + hash_decrypted + "\n";
            jTextArea1.setText(text);
        } catch (IOException ex) {
            Logger.getLogger(AES.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex ) {
            Logger.getLogger(AES.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HashMd5DecryptActionPerformed

    private void BrowseDecryptedFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseDecryptedFileActionPerformed
        // TODO add your handling code here:
        jFileChooser1.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = jFileChooser1.showOpenDialog(this);
        if (result == jFileChooser1.APPROVE_OPTION) {
            File selectedFile = jFileChooser1.getSelectedFile();
            int i = selectedFile.getName().lastIndexOf(".");
            filename = selectedFile.getName().substring(0, i);
            if(i >= 0) {
                extension = selectedFile.getName().substring(i + 1);
            }

            JOptionPane.showMessageDialog((Component)null, "Selected file: " + selectedFile.getAbsolutePath());
            decrypted_path = Paths.get(selectedFile.getAbsolutePath(), new String[0]);
            jTextField4.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_BrowseDecryptedFileActionPerformed

    private void BrowseRawFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseRawFileActionPerformed
        // TODO add your handling code here:
        jFileChooser1.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = jFileChooser1.showOpenDialog(this);
        if (result == jFileChooser1.APPROVE_OPTION) {
            File selectedFile = jFileChooser1.getSelectedFile();
            int i = selectedFile.getName().lastIndexOf(".");
            filename = selectedFile.getName().substring(0, i);
            if(i >= 0) {
                extension = selectedFile.getName().substring(i + 1);
            }

            JOptionPane.showMessageDialog((Component)null, "Selected file: " + selectedFile.getAbsolutePath());
            raw_path = Paths.get(selectedFile.getAbsolutePath(), new String[0]);
            jTextField3.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_BrowseRawFileActionPerformed

    private void HashMd5RawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HashMd5RawActionPerformed
        try {
            // TODO add your handling code here:
            byte[] file = Files.readAllBytes(raw_path);
            byte[] hash = MessageDigest.getInstance("MD5").digest(file);
            hash_raw = DatatypeConverter.printHexBinary(hash);
            text += "Raw file hashed to MD5 is: " + hash_raw + "\n";
            jTextArea1.setText(text);
        } catch (IOException ex) {
            Logger.getLogger(AES.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex ) {
            Logger.getLogger(AES.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HashMd5RawActionPerformed

    private void SaveDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDecryptActionPerformed
        // TODO add your handling code here:
        if(doneDecrypt) {
            try {
                FileOutputStream ex = new FileOutputStream(System.getProperty("user.dir")+ "\\" + filename + "_decrypted." + extension);
                    ex.write(decrypted);
                    ex.close();
                    JOptionPane.showMessageDialog((Component)null, "Save file: " + System.getProperty("user.dir") + "\\" +  filename + "_decrypted." + extension);
                        textPane2 = textPane2 + "Save file: " + System.getProperty("user.dir") + "\\" + filename + "_decrypted." + extension + "\n";
                        jTextPane2.setText(textPane2);
                    } catch (IOException var3) {
                        Logger.getLogger(AES.class.getName()).log(Level.SEVERE, (String)null, var3);
                    }
                }
    }//GEN-LAST:event_SaveDecryptActionPerformed

    private void SaveAsDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsDecryptActionPerformed
        // TODO add your handling code here:
        jFileChooser1.setCurrentDirectory(new File("user.dir"));
        int retrival = jFileChooser1.showSaveDialog((Component)null);
        if(doneDecrypt) {
            if(retrival == 0) {
                try {
                    FileOutputStream ex = new FileOutputStream(jFileChooser1.getSelectedFile() + "." + extension);
                    ex.write(decrypted);
                    ex.close();
                    JOptionPane.showMessageDialog((Component)null, "Save file: " + jFileChooser1.getSelectedFile().getAbsolutePath() + "." + extension);
                    textPane2 = textPane2 + "Save file: " + jFileChooser1.getSelectedFile().getAbsolutePath() + "." + extension + "\n";
                    jTextPane2.setText(textPane2);
                } catch (IOException var4) {
                    Logger.getLogger(AES.class.getName()).log(Level.SEVERE, (String)null, var4);
                }
            }
        } else {
            JOptionPane.showMessageDialog((Component)null, "You haven\'t decrypted any files");
        }
    }//GEN-LAST:event_SaveAsDecryptActionPerformed

    private void DecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecryptActionPerformed
        // TODO add your handling code here:
        String key = jTextField2.getText();
        time = 0L;
        long startTime = System.currentTimeMillis();

        try {
            if(jTextField2.getText() != null) {
                encrypted = Files.readAllBytes(path);
                decrypted = decrypt(encrypted, key);
                JOptionPane.showMessageDialog((Component)null, "Decrypting Done. Please Save File!");
                textPane2 = textPane2 + "Decrypting Done. Please Save File!\n";
                doneDecrypt = true;
            } else {
                JOptionPane.showMessageDialog((Component)null, "Please input key and browse text file before decrypting");
                textPane2 = textPane2 + "Please input key and browse file before decrypting\n";
            }

            jTextPane2.setText(textPane2);
        } catch (Exception var7) {
            Logger.getLogger(AES.class.getName()).log(Level.SEVERE, (String)null, var7);
        }

        long endTime = System.currentTimeMillis();
        time = endTime - startTime;
        JOptionPane.showMessageDialog((Component)null, "Time to decrypting file: " + time + " milliseconds");
        textPane2 = textPane2 + "Time to decrypting file: " + time + " milliseconds\n";
        jTextPane2.setText(textPane2);
    }//GEN-LAST:event_DecryptActionPerformed

    private void BrowseTab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseTab2ActionPerformed
        // TODO add your handling code here:
        jFileChooser1.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = jFileChooser1.showOpenDialog(this);
        if (result == jFileChooser1.APPROVE_OPTION) {
            File selectedFile = jFileChooser1.getSelectedFile();
            int i = selectedFile.getName().lastIndexOf(".");
            filename = selectedFile.getName().substring(0, i);
            if(i >= 0) {
                extension = selectedFile.getName().substring(i + 1);
            }

            JOptionPane.showMessageDialog((Component)null, "Selected file: " + selectedFile.getAbsolutePath());
            path = Paths.get(selectedFile.getAbsolutePath(), new String[0]);
            textPane2 = textPane2 + "Load file Done!\nPlease click Decrypt Button!\n";
            jTextPane2.setText(textPane2);
        }
    }//GEN-LAST:event_BrowseTab2ActionPerformed

    private void SaveEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveEncryptActionPerformed
        // TODO add your handling code here:
        if(doneEncrypt) {
            try {
                FileOutputStream ex = new FileOutputStream(System.getProperty("user.dir") + "\\" + filename + "_encrypted." + extension);
                    ex.write(encrypted);
                    ex.close();
                    JOptionPane.showMessageDialog((Component)null, "Save file: " + System.getProperty("user.dir") + "\\" + filename + "_encrypted." + extension);
                        textPane1 = textPane1 + "Save file: " + System.getProperty("user.dir") + "\\" + filename + "_encrypted." + extension + "\n";
                        jTextPane1.setText(textPane1);
                    } catch (IOException var3) {
                        Logger.getLogger(AES.class.getName()).log(Level.SEVERE, (String)null, var3);
                    }
                }
    }//GEN-LAST:event_SaveEncryptActionPerformed

    private void SaveAsEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsEncryptActionPerformed
        // TODO add your handling code here:
        jFileChooser1.setCurrentDirectory(new File("user.dir"));
        int retrival = jFileChooser1.showSaveDialog((Component)null);
        if(doneEncrypt) {
            JFileChooser var10001 = jFileChooser1;
            if(retrival == 0) {
                try {
                    FileOutputStream ex = new FileOutputStream(jFileChooser1.getSelectedFile() + "." + extension);
                    ex.write(encrypted);
                    ex.close();
                    JOptionPane.showMessageDialog((Component)null, "Save file: " + jFileChooser1.getSelectedFile().getAbsolutePath() + "." + extension);
                    textPane1 = textPane1 + "Save file: " + jFileChooser1.getSelectedFile().getAbsolutePath() + "." + extension + "\n";
                    jTextPane1.setText(textPane1);
                } catch (Exception var4) {
                    Logger.getLogger(AES.class.getName()).log(Level.SEVERE, (String)null, var4);
                }
            }
        } else {
            JOptionPane.showMessageDialog((Component)null, "You haven\'t encrypted any files");
        }
    }//GEN-LAST:event_SaveAsEncryptActionPerformed

    private void EncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncryptActionPerformed
        // TODO add your handling code here:
        time = 0L;
        long startTime = System.currentTimeMillis();
        String key = jTextField1.getText();

        try {
            if(jTextField1.getText() != null) {
                clean = Files.readAllBytes(path);
                encrypted = encrypt(clean, key);
                JOptionPane.showMessageDialog((Component)null, "Encrypting Done. Please Save File!");
                textPane1 = textPane1 + "Encrypting Done. Please Save File!\n";
                doneEncrypt = true;
                jTextPane1.setText(textPane1);
            } else {
                JOptionPane.showMessageDialog((Component)null, "Please input key and browse file before encrypting");
                textPane1 = textPane1 + "Please input key and browse file before encrypting\n";
                jTextPane1.setText(textPane1);
            }
        } catch (Exception var7) {
            Logger.getLogger(AES.class.getName()).log(Level.SEVERE, (String)null, var7);
        }

        long endTime = System.currentTimeMillis();
        time = endTime - startTime;
        JOptionPane.showMessageDialog((Component)null, "Time to encrypting file: " + time + " milliseconds");
        textPane1 = textPane1 + "Time to encrypting file: " + time + " milliseconds\n";
        jTextPane1.setText(textPane1);
    }//GEN-LAST:event_EncryptActionPerformed

    private void BrowseTab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseTab1ActionPerformed
        // TODO add your handling code here:
        jFileChooser1.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = jFileChooser1.showOpenDialog(this);
        if (result == jFileChooser1.APPROVE_OPTION) {
            File selectedFile = jFileChooser1.getSelectedFile();
            int i = selectedFile.getName().lastIndexOf(".");
            filename = selectedFile.getName().substring(0, i);
            if(i >= 0) {
                extension = selectedFile.getName().substring(i + 1);
            }

            JOptionPane.showMessageDialog((Component)null, "Selected file: " + selectedFile.getAbsolutePath());
            path = Paths.get(selectedFile.getAbsolutePath(), new String[0]);
            textPane1 = textPane1 + "Load file Done!\nPlease click Encrypt Button!\n";
            jTextPane1.setText(textPane1);
        }
    }//GEN-LAST:event_BrowseTab1ActionPerformed

    private void EncryptKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncryptKeyActionPerformed
        // TODO add your handling code here:
        try {
            if (!areKeysPresent()) {
                generateKey();
            }   
            ObjectInputStream inputStream = null;
            inputStream = new ObjectInputStream(new FileInputStream(PUBLIC_KEY_FILE));
            final PublicKey publicKey = (PublicKey) inputStream.readObject();          
            final byte[] cipherText = RSA.encrypt(jTextField1.getText(), publicKey);
            FileOutputStream ex = new FileOutputStream("C:/keys/keyAES_encrypt.txt");
            ex.write(cipherText);
            ex.close();         
            JOptionPane.showMessageDialog(null, "Encrypting AESKey with RSA Done");
        } catch (Exception e) {
            e.printStackTrace();
        }   
    }//GEN-LAST:event_EncryptKeyActionPerformed

    private void DecryptKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecryptKeyActionPerformed
        // TODO add your handling code here:
        try {
            if (!areKeysPresent()) {
                generateKey();
            }
            
            ObjectInputStream inputStream = null;
            inputStream = new ObjectInputStream(new FileInputStream(PRIVATE_KEY_FILE));
            final PrivateKey privateKey = (PrivateKey) inputStream.readObject();
            byte[] data = Files.readAllBytes(encrypt_key);
            final String plainText = RSA.decrypt(data, privateKey);
            JOptionPane.showMessageDialog(null, "Decrypting AES Key with RSA Done");
            jTextField2.setText(plainText);
        } catch (Exception e) {
            e.printStackTrace();
        }   
    }//GEN-LAST:event_DecryptKeyActionPerformed
    List<String> fileLines;
    Path encrypt_key = null;
    private void BrowseEncryptKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseEncryptKeyActionPerformed
        // TODO add your handling code here:
        jFileChooser1.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = jFileChooser1.showOpenDialog(this);
        if (result == jFileChooser1.APPROVE_OPTION) {
            File selectedFile = jFileChooser1.getSelectedFile();
            String text = "";
            JOptionPane.showMessageDialog(null,"Selected encrypted key: " + selectedFile.getAbsolutePath());   
            Path path = Paths.get(selectedFile.getAbsolutePath());
            encrypt_key = path;
        }
    }//GEN-LAST:event_BrowseEncryptKeyActionPerformed
    String text = "";
    String hash_raw = "";
    String hash_decrypted = "";
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseDecryptedFile;
    private javax.swing.JButton BrowseEncryptKey;
    private javax.swing.JButton BrowseRawFile;
    private javax.swing.JButton BrowseTab1;
    private javax.swing.JButton BrowseTab2;
    private javax.swing.JButton Checksum;
    private javax.swing.JButton Decrypt;
    private javax.swing.JButton DecryptKey;
    private javax.swing.JButton Encrypt;
    private javax.swing.JButton EncryptKey;
    private javax.swing.JButton HashMd5Decrypt;
    private javax.swing.JButton HashMd5Raw;
    private javax.swing.JButton SaveAsDecrypt;
    private javax.swing.JButton SaveAsEncrypt;
    private javax.swing.JButton SaveDecrypt;
    private javax.swing.JButton SaveEncrypt;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JLabel key;
    // End of variables declaration//GEN-END:variables
}
